services:
  backend:
    build:
      context: ./backend/
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/
    ports:
      - "3000:3000"

  # service that's invoked explicitly to run the manugen-ai command
  manugen:
    profiles:
      - cli
    build:
      context: ./packages/
    command: "uv run manugen /content/"
