# this compose file is used to run the backend with a PostgreSQL database for
# persistent session management, as well as future development that may require
# a database

# to use this compose file, add the following lines to your .env file;
# be sure to replace <random_password_here> with a secure password of your
# choice

# POSTGRES_USER="postgres"
# POSTGRES_PASSWORD=<random_password_here>
# POSTGRES_HOST="db"
# POSTGRES_PORT="5432"
# POSTGRES_DB="manugen"

services:
  backend:
    environment:
      # yamllint disable-line rule:line-length
      - "SESSION_DB_CONN_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    depends_on:
      - db

  # session database for ADK
  db:
    restart: unless-stopped
    image: postgres:16
    env_file:
      - .env
