services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8900:8000"
    env_file:
      - .env
    environment:
      - "OLLAMA_API_BASE=http://host.docker.internal:11434"
      - "POSTGRES_HOST=db"
      - "POSTGRES_DB=manugen"
      - "SESSION_DB_CONN_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    volumes:
      - ./packages/manugen-ai/src/:/opt/manugen-ai/src/
      - ./packages/manugen-ai/tests/:/opt/manugen-ai/tests/
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
    ports:
      - "8901:5173"
    environment:
      - "VITE_API=http://localhost:8900"
      - "VITE_TITLE=Manugen AI"

  # service that's invoked explicitly to run the manugen-ai command
  manugen:
    profiles:
      - cli
    build:
      context: ./packages/
    env_file:
      - .env
    environment:
      - "OLLAMA_API_BASE=http://host.docker.internal:11434"
    command: "uv run manugen /content/"

  # session database for ADK
  db:
    image: postgres:16
    env_file:
      - .env
