services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    environment:
      - "OLLAMA_API_BASE=http://host.docker.internal:11434"
      - "POSTGRES_HOST=db"
      - "POSTGRES_DB=manugen"
      - "FLAGEMBEDDING_CACHE_DIR=/opt/model_cache/"
    volumes:
      # in case we're using FlagEmbedding models,
      # we'll want to cache them on the host
      - ./model_cache/:/opt/model_cache/
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend/
    environment:
      - "VITE_API=http://localhost:8900"
      - "VITE_TITLE=Manugen AI"

  # session database for ADK
  db:
    image: postgres:16
    env_file:
      - .env
