services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    environment:
      - "OLLAMA_API_BASE=http://host.docker.internal:11434"
      - "POSTGRES_HOST=db"
      - "POSTGRES_DB=manugen"
      - "SESSION_DB_CONN_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend/
    environment:
      - "VITE_API=http://localhost:8900"
      - "VITE_TITLE=Manugen AI"

  # service that's invoked explicitly to run the manugen-ai command
  manugen:
    profiles:
      - cli
    build:
      context: ./packages/
    env_file:
      - .env
    environment:
      - "OLLAMA_API_BASE=http://host.docker.internal:11434"
    command: "uv run manugen /content/"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # session database for ADK
  db:
    image: postgres:16
    env_file:
      - .env
