[tool.ruff]
target-version = "py312"
line-length = 88
fix = true
lint.select = [
  # pyflakes
  "F",
  # isort
  "I",
  # for flake8-print
  "T20",
]
# Ignore `F401` (unused imports) for `__init__.py` file
lint.per-file-ignores."__init__.py" = [ "F401" ]
