[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "manugen-ai"
version = "0.1.0"
description = ""
readme = "README.md"
license = "BSD-3-Clause"
authors = [
  { name = "Dave Bunten", email = "david.bunten@cuanschutz.edu" },
  { name = "Vincent Rubinetti", email = "vincent.rubinetti@cuanschutz.edu" },
  { name = "Milton Pividori", email = "milton.pividori@cuanschutz.edu" },
  { name = "Faisal Alquaddoomi", email = "faisal.alquaddoomi@cuanschutz.edu" },
]
dependencies = [
    "google-adk (>=1.2.1,<2.0.0)",
    "cyclopts (>=3.17.0,<4.0.0)",
    "python-dotenv>=1.1.0",
    "litellm>=1.72.1",
    "ipython>=9.2",
    "nbconvert>=7.16.6",
    "pygit2>=1.18",
]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]


scripts.manugen = "manugen_ai.cli:app"

[dependency-groups]
dev = [
  "black>=25.1,<26",
  "pytest>=8.4,<9",
  "pytest-asyncio>=1",
]

[tool.hatch.build.targets.sdist]
include = [ "src/manugen_ai" ]

[tool.hatch.build.targets.wheel]
include = [ "src/manugen_ai" ]

[tool.hatch.build.targets.wheel.sources]
"src/manugen_ai" = "manugen_ai"
