[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "manugen-ai"
version = "0.1.0"
description = ""
readme = "README.md"
license = "BSD-3-Clause"
authors = [
  { name = "Dave Bunten", email = "david.bunten@cuanschutz.edu" },
  { name = "Vincent Rubinetti", email = "vincent.rubinetti@cuanschutz.edu" },
  { name = "Milton Pividori", email = "milton.pividori@cuanschutz.edu" },
  { name = "Faisal Alquaddoomi", email = "faisal.alquaddoomi@cuanschutz.edu" },
]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

dependencies = [
  "cyclopts>=3.17,<4",
  "google-adk>=1.2.1,<2",
  "ipython>=9.2",
  "jsonschema>=4.24.0",
  "litellm>=1.72.1",
  "nbconvert>=7.16.6",
  "psycopg2-binary>=2.9.10",
  "pygit2>=1.18",
  "python-dotenv>=1.1",
  "requests>=2.32.3",
]
scripts.manugen = "manugen_ai.cli:app"

[dependency-groups]
dev = [
  "black>=25.1,<26",
  "jupyterlab>=4.4.3",
  "nbclient>=0.10.2",
  "nbformat>=5.10.4",
  "pytest>=8.4,<9",
  "pytest-asyncio>=1",
]

[tool.hatch.build.targets.sdist]
include = [ "src/manugen_ai" ]

[tool.hatch.build.targets.wheel]
include = [ "src/manugen_ai" ]

[tool.hatch.build.targets.wheel.sources]
"src/manugen_ai" = "manugen_ai"
