---
# used for running tests
name: tests
on:
  push:
    branches: [main]
    paths:
      - "packages/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/**"
  workflow_dispatch:

jobs:
  run_package_tests:
    strategy:
      matrix:
        python_version: ["3.12"]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | sh
      - name: Run ollama
        run: |
          ollama serve &
          ollama pull llama3.2:3b
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Run pytest
        # cd into the packages dir and run pytest
        # note: we skip notebooks as these are for reporting only.
        run: cd packages/manugen-ai && uv run --frozen pytest -m "not notebooks"
        env:
          # use the same models here to keep ci run duration low
          # by avoiding extra downloads
          MAI_GENERAL_MODEL_NAME: "openai/llama3.2:3b"
          MAI_CODE_SPECIALIST_MODEL_NAME: "openai/llama3.2:3b"
