---
name: pre-commit-checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pre_commit_checks:
    runs-on: ubuntu-24.04
    steps:
      # checks out the repo
      - uses: actions/checkout@v4
      # run pre-commit
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.1
