---
# used for running tests
name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_package_tests:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-24.04, macos-14]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Run pytest
        # cd into the packages dir and run pytest
        run: cd packages/manugen-ai && uv run --frozen pytest